[Feat] #6 - 동굴 생성뷰 UI와 하단 CTA버튼 공용컴포넌트를 만들었습니다.
Team-Growthook/Growthook-iOS pull request #11
Opened 2023-11-16 04:22 UTC by frohsch

## 🌿 문제

- 하단에 있는 버튼을 만들었습니다. enum으로 뽑아놨으니 필요하신 분은 사용해주세요 !! 
`BottomCTAButton(type: .createNewCave)`
- textField 뷰도 만들어 놓기는 했는데 디자인 자체가 텍스트뷰로 바뀌는 이슈가 있어 추후 수정해야할 것 같습니다. -> 아마 저만 쓸 것 같아서 제가 수정해놓을게요 !!

## 🌱 작업한 내용

- 동굴 생성뷰 U 구현
- 동굴 생성 완료시 나타나는 보관함 상세뷰 하단 Empty 뷰 구현 (보관함 상세뷰에 붙이기)
이에 따른 ViewController 하나도 임의로 만들어 놨습니다.
- BottomCTAButton 구현

## 📷 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| GIF | <img src = "https://github.com/Team-Growthook/Growthook-iOS/assets/89457040/c71e6c84-c2ce-4a35-b642-1e4edf5516d8" width ="250">|

## 🍀 관련 이슈

- Resolved: #6

2023-11-16 07:09 UTC, kj9470 commented on Growthook/Growthook/Presentation/Common/UIComponents/BottomCTAButton.swift
> +    case save
와 버튼 지대짱이다 ~!!

2023-11-16 07:11 UTC, kj9470 commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +    }
와 애니메이션 기깔나네여

2023-11-16 07:13 UTC, kj9470 approved these changes
수고하셨슴니다 민주샘~~♥️

2023-11-17 14:46 UTC, PecanPiePOS requested changes
어우 기깔나게 잘 만드셨네요 
민주님 좀 하시네요. 백엔드 하시죠?

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Application/SceneDelegate.swift
> +                    let naviVC = UINavigationController(rootViewController: CreateCaveViewController())
p3
기존의 TabBarController 로 변경해주세요~!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Global/Extension/UIView+.swift
> +    }
p2
extension 이 혹시 UIView 에서 하신 이유를 알 수 있을까요??

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Common/UIComponents/BottomCTAButton.swift
> +    }
p3
혹시 메서드가 아닌 직접 프로퍼티를 사용하신 이유가 있을까용??

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/View/CreateCaveView.swift
> +    }
p4
BaseView 쓰면 편해요~~

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/View/CreateCaveView.swift
> +    }
p3
어떤 이유로 `@discardableResult` 를 쓰신걸까요?

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/View/EmptySeedView.swift
> +    }
p4
BaseView 쓰시면 편해요~2

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +    private let createCaveView = CreateCaveView()
p5
한칸 띄워주세요~!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +    }
p2
View Life Cycle 상 가장 먼저 불리는 loadView 이기 때문에 lifeCycle 메서드 중에서는 가장 상단에 위치해주시면 좋겠습니다~!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/AlertBuilder.swift
> +    }
p1
오 Builder 를 쓰셨네요!
혹시 해당 내용에 대해서는 다른 팀원분들이 이해하기 쉽게 설명을 해주셨으면 좋겠네요~!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/AlertBuilder.swift
> +    }
p3
그리고 ViewModel 에 들어가있는데 따로 폴더링을 하실 생각이 있으신가요?!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
> +    var name: BehaviorRelay<String> { get }
p1
func 으로 처리해주세요! 😃

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
> +    var name: BehaviorRelay<String> { get }
p1
Input 과 Output 에 같은 변수명의 프로퍼티가 있다면 혼동하기 쉽기도 합니다. 물론 Input 에서 func 으로 처리해주신다면 문제가 없겠지만요!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
> +    var caveModel: BehaviorRelay<CreateCaveModel> { get }
p3
caveModel 이라는 data 를 보내는거라면 변수명을 조금 더 명확하게 해주시는게 좋아보입니다!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
> +    var switchStatus: BehaviorRelay<Bool> = BehaviorRelay(value: false)
p2
input - type - output 순서로 바꿔주시면 좋을 것 같습니다~!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
> +    }
p2
왜 isValid 만 이곳에 있을까요?!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +            .disposed(by: disposeBag)
p3
`guard let self ~` 를 안 쓰신 이유가 있을까요??!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +            .disposed(by: disposeBag)
p3
isValid 는 input 아닌가요?! input 을 붙여주시면 좋을 것 같습니다~!

2023-11-17 14:46 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +}
p2
요건 지워주시고 올려주세요~!

2023-11-21 16:13 UTC, frohsch commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +}
넵!!

2023-11-21 16:17 UTC, frohsch commented on Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
> +            .disposed(by: disposeBag)
아 웬만하면 guard let 으로 self를 언랩핑 해주는 것이 좋군요 !! 배워갑니당...

2023-11-21 17:12 UTC, closed without merging