[Fix] #6+ - 파일 에러를 해결하고 코드리뷰를 반영했습니다.
Team-Growthook/Growthook-iOS pull request #14
Opened 2023-11-21 17:06 UTC by frohsch

## 🌿 문제

- 프로젝트 내부에 파일이 안 보이는 문제를 해결했습니다. 이후 #11 의 코드리뷰를 반영했습니다. 

## 🌱 작업한 내용

- 코드리뷰를 반영하여 컨벤션을 맞추고, 불필요한 코드를 삭제했습니다.

## 🍀 관련 이슈

- Resolved: #6

2023-11-27 10:05 UTC, kj9470 approved these changes
수고하셨습니댜아아아

2023-12-12 14:22 UTC, PecanPiePOS requested changes
고생하셨습니다! p2 붙은것만 해결 부탁드릴게요~!

2023-12-12 14:22 UTC, PecanPiePOS commented on Growthook/Growthook/Global/Extension/UIView+.swift
> +    }
p4
혹시 해당 메서드는, 하프 modal 로 present 됐을시에는 잘 뜨나요??

2023-12-18 07:38 UTC, PecanPiePOS approved these changes

2023-12-18 07:41 UTC, merged