[Feature] #28 - 인사이트 작성 화면을 구현했습니다.
Team-Growthook/Growthook-iOS pull request #32
Opened 2023-12-21 16:08 UTC by PecanPiePOS

## 🌿 문제

- 앱 내의 주요 컨텐트는 `TextView` 와 `TextField` 로 이루어져 있어 프로젝트 초기에 모두가 사용할 수 있는 컴포넌트를 만들었습니다. 
    - 하지만 custom 컴포넌트 내에 `delegate` 을 사용하는 특성상 Rx 와 겹치면, 결국 내부에서 사용된 delegate 은 무시가 되게 됩니다. 
    👀 **❗️Rx 와 각 Text 컴포넌트의 `controlEvent` 를 이어서 VC 에서 바인딩만 하면 쉽게 사용할 수 있는 것을 만들어야 했습니다.❗️**
    - `Reactive` 에서 `extension` 을 뽑아 각 클래스에서 필요한 프로퍼티를 만들었습니다. 
        - `UITextField` 의 경우, 내부에서 사용되는 Text 를 `.scan` 으로 확인하며, 글자수를 체크했습니다. 또한, `TextField` 는 `UIControl` 을 상속하므로, 이 `ControlEvent` 에 대한 `Observable` 을 따로 뽑아 `delegate` 을 겹쳐 사용하는 불상사를 막았습니다.
        - `UITextField` 의 경우, 마찬가지로, 글자수를 확인했습니다만, `UIControl` 을 상속하지 않는 `class` 로써 `TextField` 에서 사용한 방법과 다르게 접근을 했습니다. `TextView` 에도 `didEndEdit`, `didBeginEdit`, `didChange` 라는 `delegate` 을 사용하는 `ControlEvent` 가 있습니다. 그래서 내부에서 3개의 메서드를 모두 호출한 후 각각 `ControlEvent` 를 `Output` 으로 방출하는 `Observable` ( `PublishRelay<UIContrl.Event> `) 을 따로 뽑아 사용했습니다.
- 그래서 이걸 가지고 작업을 진행하시면 될 것 같습니다!

## 🌱 작업한 내용

- [ ] ViewModel 주입을 통해 여러 VC 에서의 데이터-UI 바인딩 이슈 최소화
- [ ] 인사이트 작성 뷰 구현
- [ ] 인사이트 동굴 선택 뷰 구현
- [ ] 인사이트 기간 선택 뷰 구현
- [ ] Text Component 를 누르면 적당한 위치로 scroll 하여 UX 를 헤치지 않게 구현
- [ ] TextView 에 키보드 위의 toolbar 를 구현하여, 
    - 화살표: 다음 Text Component 로 이동하거나, 키보드를 내릴 수 있게 함
    - 키보드: 키보드를 내립니다. 

## 📷 스크린샷

https://github.com/Team-Growthook/Growthook-iOS/assets/89404664/13b237aa-c4dd-4ab6-b371-4403e4e8e537

## 🍀 관련 이슈

- Resolved: #28

2023-12-21 16:10 UTC, PecanPiePOS commented on Growthook/Growthook/Global/Extension/Reactive+UIControl.swift
> +import RxSwift
아마 그래서 이번 pr 은 나중에 직접 Xcode 로 열어서 확인하는게 훨씬 빠르게 이해가 될 겁니다!

2023-12-21 18:13 UTC, frohsch requested changes
우왕짱이당..

2023-12-21 18:13 UTC, frohsch commented on Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
p2. 이 파일 Line 138쯤에.. let toolBar = UIToolbar() 이 부분 때문에 Toolbar의 레이아웃이 안잡혔다는 레이아웃 warning이 뜹니다. 그래서 제가 찾아봤는데 let toolBar = UIToolbar(frame: CGRect(x: 0, y: 0, width: 100, height: 100)) 이런식으로 프레임을 지정해주면 되더라구요.. 프레임에 .zero도 넣어봤는데 그러면 계속 warning이 뜨고 어떤 숫자를 꼭 넣어줘야 했습니다.. 이게 왜 그런지는 모르겠지만 아주 긴 레이아웃 오류는 보기 싫으니까 고쳐주시면 감사하겠습니다 !!

2023-12-22 05:30 UTC, cjs1399 approved these changes
심 교수님 수고하셨습니당

2023-12-22 06:13 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
이거 제가 새롭게 만든 거 에서는 수정한 사항인데, 이거까지 수정해서 올리겠습니다~

2023-12-22 06:19 UTC, frohsch approved these changes

2023-12-22 16:50 UTC, merged