[Feat] #34 - 스크랩 기능 및 toast 추가
Team-Growthook/Growthook-iOS pull request #35
Opened 2023-12-23 15:38 UTC by kj9470

## 🌿 문제

- 스크랩 기능을 구현하지 않아 추가했습니다
- 자꾸 package 커밋이 떠서 gitignore 파일 수정했습니다.
- 그리고 인사이트 스크랩 버튼 누르고 스크롤 시 다시 원래대로 돌아가는데, 모델에 있는 값 가져와서 보여주기 때문에 서버통신 이후엔 괜찮을 것 같습니다.

## 🌱 작업한 내용

- 스크랩 기능 구현
- gitignore 파일 수정
- 셀 스크롤 시 꼬임 현상 해결
- 스크랩, 인사이트 이동, 삭제 시 토스트 메시지 추가
- 토스트 메시지에 그림자 추가

## 📷 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| GIF | <img src = "https://github.com/Team-Growthook/Growthook-iOS/assets/48792069/4045ae73-7c57-46d2-b9d8-c193e28bfd0d" width ="250">|

## 🍀 관련 이슈

- Resolved: #34

2023-12-23 16:45 UTC, PecanPiePOS requested changes
Notification Observer 를 Remove 하는 곳이 있을까요?
그거는 memoryLeak 때문에 수정해야할 것 같아요!

2023-12-23 16:45 UTC, PecanPiePOS commented on .gitignore
> +Package.resolved
와 잠만 이게 안돼있었어? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 어쩐지 계속 뜨드라

2023-12-23 16:45 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
> +    }
p4
나중에 Observable 로 바꿔봐요~~

2023-12-23 16:45 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
> +        )
p2
viewmodel 주입해서 사용해보시죠~ 
하지만 지금말고 다음에!

2023-12-23 16:45 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
> +        )
p2
근데 이 Notification 의 Observer 를 remove 하는건 어디에 있죠?!

2023-12-24 04:20 UTC, kj9470 commented on Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
> +        )
홈 뷰에는 추가했었는데 보관함 뷰에는 깜빡했네요 ! 추가하겠습니당

2023-12-24 04:22 UTC, kj9470 commented on Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
> +        )
홈뷰컨, 보관함 뷰컨에서 remove 하고 있습니다 !

2023-12-24 04:22 UTC, kj9470 commented on .gitignore
> +Package.resolved
나도 이거 왜 계속 뜨나 했어ㅡㅡ

2023-12-24 04:22 UTC, kj9470 commented on Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
> +    }
넹 ~~

2023-12-26 16:14 UTC, PecanPiePOS approved these changes

2023-12-26 16:14 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
> +        )
앗 감사합니당!

2023-12-26 16:21 UTC, merged