[Feat] #3 - 메인 뷰 UI 구현
Team-Growthook/Growthook-iOS pull request #7
Opened 2023-11-13 09:40 UTC by kj9470

## 🌿 문제

- 메인뷰 UI만 구현했습니다.
- MVVM 처음 적용해보는 거라서 훈수 마구마구 부탁드려요

## 🌱 작업한 내용

- 메인 뷰 UI 구현

## 📷 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| GIF | <img src = "https://github.com/Team-Growthook/Growthook-iOS/assets/48792069/fa84438c-9e8a-45d3-b268-a00227b22773" width ="250">|

## 🍀 관련 이슈

- Resolved: #3

2023-11-13 12:18 UTC, cjs1399 approved these changes
리드님 코드 작성하시느라 수고 많으셨습니다! MVVM을 잘 모르기에 그래도 보면서 배워갑니다..!

2023-11-14 02:52 UTC, PecanPiePOS requested changes
처음 MVVM + RxSwift 쓰시는데에 고생이 많습니다!
피드백 요청사항이 꽤나 디테일한데 최소한의 디테일이라 맞춰주셔야 MVVM 을 제대로 사용하는거라고 생각합니다! 조금만 더 고생해주세요!!!

2023-11-14 02:52 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/Model/HomeViewModel.swift
> +}
p1
현재 정이님의 뷰의 Input 은 어떤걸까요??
전에 말씀드렸다시피 ViewModel 에서의 Input 이란, 
1. 사용자의 이벤트 입력
2. 뷰컨트롤러 사이클에 의한 입력
이 있습니다.

그런데 지금 어떤 이벤트에 대한 처리가 하나도 되어있지 않습니다!
`caveCollectionViewBind()`, `insightListCollectionViewBind()`
모두 View 에서 다루어야 하는 UIBinding 의 메서드이지 ViewModel 에서는 Input 이 아닙니다.

전에 말씀드린 KickStarter 의 깃헙 레포를 보시거나 하시면 도움이 될 것 같습니다.
예시를 말씀드릴테니 다른 곳에 적용해보시기 바랍니다.

현재 홈화면 자체적으로는 데이터 처리 구현이 많이 없어서 예시가 이상할 수 있지만 일단 보시면,
예시) func caveTapped()
-> 동굴 CollectionView 에 있는 동굴 item 이 tap 됐을 때 발생하는 로직입니다.

2023-11-14 02:52 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/Model/HomeViewModel.swift
> +}
p1
UI 를 그리는 모든 데이터는 이곳에서 처리를 해야합니다.
즉, 어떤 것이 있을까요?
예를 들면, 동굴 CollectionView 의 item 들이 있겠습니다.

현재, Model 에서 더미데이터를 부르는데 Model 은 View 나 ViewModel 과 독립적이어야 합니다.
지금 단계에서는 Model.caveprofileDummyData() 를 ViewModel 에서 구현하여 Output 으로 내보내야 하지만
이 또한 지양해야할 점입니다. 의존성이 생기니까요.

어쩃거나 지금은 위에서 말씀드린것처럼 하면 됩니다.

2023-11-14 02:52 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/Model/HomeViewModel.swift
> +}
전에 가르쳐드렸을 때 다 말씀 드렸습니다!
UI 를 구성하는 Data 를 Output 으로 내보내는 것입니다!
RxSwift 를 통해서요!

2023-11-14 02:52 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/Model/HomeViewModel.swift
> +    }
p1
데이터를 가져오는 시점은 View 를 그릴 때가 아니라, ViewModel 이 초기화 됐을 때 여야합니다.
혹시 차이점을 아시겠나요??

View 를 그릴때 가져오는 것은, 정이님이 쓰신것처럼 "bind 를 할때" 라는 메서드를 활용해서 ViewController 에 사용한것이고
ViewModel 이 초기화 됐을 때 가져오는 것은, 이 ViewModel 이 초기화가 됐을 때 부르는 것이구요.

위에서 말씀드린 Input 의 정의를 잘 생각해보시면 좋을 것 같습니다~!
기본적으로 데이터가 구성되어야 하는 것들은 Input 에 들어갈 수도 있지만, 그것은 viewDidLoad, ViewWillAppear, ViewWillDisappear 등에서 특정 시점에 불려야 하는 것을 따로 Input 으로 넣을 수 있습니다.
그 외의 처음 초기화가 됐을 때, 즉 처음 데이터가 구성이 되어서 UI 가 그려져야하는 부분은 ViewModel 이 초기화 될 때 부르는게 맞겠죠!

수정해주시면 감사하겠습니다~!

2023-11-14 02:52 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/View/HomeCaveView.swift
> +    }
p1
이것도 헷갈릴 수 있는 사항인데요
caveCollectionView 가 dispose 되는 것이 HomeCaveView 의 disposeBag 입니다. 
하지만 caveCollectionView 의 UI 를 바인딩하는 것은 ViewController 겠죠? 그러면 disposeBag 은 ViewController disposeBag 입니다. 서로 다른 disposeBag 을 사용하기 때문에 나중에 관리하기에 문제가 생길 수 있습니다.
View 에서는 ( Controller 가 X ) 되도록 Rx 의 사용을 줄여주세요! 뭐 특정 ControlProperty 를 만든는게 아니라면 말이죠!

2023-11-14 02:52 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/View/HomeCaveView.swift
> +    }
혹은, disposeBag 의 문제라면
나중에 Controller 에서의 caveCollectionView 의 UIBinding 에서 dispose 를 Controller 의 disposeBag 이 아닌, HomeCaveView 인스턴스의 disposeBag 으로 설정하시면 될 것 같습니다.

2023-11-17 12:45 UTC, PecanPiePOS reviewed
수정이 조금 더 필요해보입니다!

2023-11-17 12:45 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Common/UIComponents/ScrapOnlyButton.swift
> +final class ScrapOnlyButton: UIButton {
p4
해당 컴포넌트는 한 곳에서만 쓰이는건가요??

2023-11-17 12:45 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift
> +    }
p2
따로 init 에서 무언가를 하지 않으면 필요없습니다!
class 에 대해서 한번 공부 더 깊게 해보시면 좋을 것 같습니다~!

2023-11-17 12:45 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
> +}
p1
Output 의 네이밍 다시 지어주시기 바랍니다!
데이터니까요! KickStarter 의 ViewModel 참고해주세요!

2023-11-17 13:27 UTC, kj9470 commented on Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift
> +    }
아 ~ 빼는거 까묵엇네용 ㅎ

2023-11-17 13:28 UTC, kj9470 commented on Growthook/Growthook/Presentation/Common/UIComponents/ScrapOnlyButton.swift
> +final class ScrapOnlyButton: UIButton {
아뇽 제 다른 뷰에서도 쓰여서 따로 빼봤습니다~

2023-11-17 13:28 UTC, kj9470 commented on Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
> +}
넹~~

2023-11-17 13:58 UTC, PecanPiePOS approved these changes
고생하셨습니다~!
천천히 다듬어보죠 우리~

2023-11-17 14:31 UTC, merged