[Feature] #71 - 소셜 로그인(APPLE) 기능 구현
Team-Growthook/Growthook-iOS pull request #78
Opened 2024-01-24 08:18 UTC by cjs1399

## 🌿 문제

- 로그인 이후 앱을 종료하고 다시 실행하여도 로그인 상태가 유지 되도록 구현

## 🌱 작업한 내용

- `SplashViewController`에서 현재 유저가 기존에 로그인을 하고 로그아웃을 하지 않은 상태면 UserDefaults에서 토큰을 가지고 와 서버와 통신이 진행되도록 구현했습니다
- 서버 통신을 진행할 때 accessToken이 만료될 경우 refreshToken을 자동으로 재발급 받을 수 있도록 처리했습니다
- 로그아웃을 할 경우 서버로 부터 받은 앱내의 정보를 모두 제거한 뒤 `isLoggedIn`의 값을 처리하여 다시 앱을 실행 할 경우 온보딩 부터 시작되게 처리하였습니다
- 회원탈퇴의 경우 아직 서버로부터 미 구현이며 구현 될 경우 바로 작업할 예정입니다.
`
    static func getFinishedActionList(with memberId: Int) -> Observable<[ActionListFinishedResponse]> {
        return provider.rx.request(.getActionListFinished(memberId: memberId))
            .asObservable()
            .mapAuthError()
            .mapError()
            .decode(decodeType: [ActionListFinishedResponse].self)
    }
`
서버 작업의 경우 위 처럼 .mapAuthError() 를 붙여주게 되면 토큰이 자동으로 재발급 되며 기존의 api 호출 기능이 다시 작동합니다

## 🍀 관련 이슈

- Resolved: #71

2024-01-24 14:57 UTC, cjs1399 reviewed
...

2024-01-24 14:57 UTC, cjs1399 commented on Growthook/Growthook/Global/Extension/Observable+.swift
> +    func mapAuthError() -> Observable<Response> {
위 mapAuthError을 사용하게 될 경우 서버 통신으로 받는 데이터가 accept 되지 않아 UI가 업데이트되지 않는 오류가 발생합니다 @PecanPiePOS

2024-01-24 15:19 UTC, PecanPiePOS requested changes
모든 사항은 P1 의 사항입니다.
변경하거나 삭제해주셔야 합니다!

2024-01-24 15:19 UTC, PecanPiePOS commented on Growthook/Growthook/Global/Extension/Observable+.swift
> +    func mapAuthError() -> Observable<Response> {
우선 DisposeBag 을 Observable 내부에 만드는게 많이 잘못됐습니다. DisposeBag 은 ARC 관련해서, 바인딩을 한 객체가 deinit 될 때 함께 없애 메모리관리를 하기 위한 것인 DisposeBag 인데 이렇게 class 내부에 넣어버리면, 순환 참조도 생길 것 같고 조금 잘못된 코드 같습니다.

2024-01-24 15:19 UTC, PecanPiePOS commented on Growthook/Growthook/Global/Extension/Observable+.swift
> +                        }
설령 이 새롭게 토큰을 받는 함수가 여기서 잘 돌아간다고 해도 여기에 있으면 안됩니다.
RxSwift 는 반응형 함수로 함수형 코드로 진행이 되는 동안, 외부의 값이 변경되게끔 하는 Side Effect 를 생성하지 않게 설계되었습니다. 그렇기 때문에 401 을 받는다면, 전에 제가 정의한 tokenExpired 라는 Error 를 전달하고, 거기서 이 메서드는 할 일을 다하게 됩니다. 새롭게 token 을 받는 로직은, VM 에서 에러에 대한 대응을 해야하는 것이지 여기서 해야하는게 아닙니다. 
즉, 다시 말하면 이건 VM 에서 로직 처리를 해야한다는 것입니다. 

mapAuthError 와 retryOriginalRequest 는 삭제해야할 것 같습니다.

2024-01-24 15:19 UTC, PecanPiePOS commented on Growthook/Growthook/Global/Extension/Observable+.swift
> +                        break
여기서도 Observable<Response> 를 리턴하는데에 반해, 401 이 아닐때는 아무것도 전달을 하지 않은 체, Disposable 을 만들어서 리턴을 하고 있으니 당연히 아무것도 전달이 안되죠. 200 이 들어오게 되면, 빈 값을 내보내는 셈이죠.

2024-01-24 15:19 UTC, PecanPiePOS commented on Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
> +            UserDefaults.standard.set(data.refreshToken, forKey: I18N.Auth.refreshToken)
왜 UserDefaults 로 토큰을 저장하시나요?!
KeyChain 을 사용해야합니다.

2024-01-24 15:21 UTC, cjs1399 commented on Growthook/Growthook/Global/Extension/Observable+.swift
> +                        break
넵 해당 코드는 삭제 후 다른 곳에서 기능 구현 할 예정입니다!

2024-01-25 02:56 UTC, kj9470 approved these changes
수고하셨습니당

2024-01-25 03:08 UTC, PecanPiePOS approved these changes
고생하셨습니다.
일단 수정사항 적어놓겠습니다.
(제가 수정하겠습니다.)
1. 401에 대한 처리를, Observable 에서 다시 처리를 하되 외부에서 토큰을 처리하게 만들어야 할 것 같습니다.  -> TokenManager 싱글톤을 사용해서 바꾸고, 메모리릭을 체크해보겠습니다.

2024-01-25 03:08 UTC, merged